name: Compilar Mod Online

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Descargar codigo
      uses: actions/checkout@v4

    - name: Configurar Java 8
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '8'

    - name: Otorgar permisos a Gradle
      run: chmod +x gradlew
      continue-on-error: true

    - name: Compilar ejecutable con Gradle
      run: |
        if [ -f ./gradlew ]; then
          ./gradlew build
        else
          gradle build
        fi
      continue-on-error: true

    - name: Guardar el archivo JAR del Mod
      uses: actions/upload-artifact@v4
      with:
        name: WTapStimpMod-Listo
        path: build/libs/*.jar
