name: Compilar Mod Online

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Descargar codigo
      uses: actions/checkout@v4

    - name: Configurar Java 8
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '8'

    - name: Compilar ejecutable con Gradle
      run: |
        echo "plugins { id 'java' }" > build.gradle.temp
        cat build.gradle >> build.gradle.temp
        mv build.gradle.temp build.gradle
        gradle build
      continue-on-error: true

    - name: Guardar el archivo JAR del Mod
      uses: actions/upload-artifact@v4
      with:
        name: WTapStimpMod-Listo
        path: build/libs/*.jar
