name: Compilar Mod Online

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Descargar codigo
      uses: actions/checkout@v4

    - name: Configurar Java 8
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '8'

    - name: Descargar Librerias Oficiales de Minecraft
      run: |
        mkdir -p libs
        wget -O libs/forge-patched.jar https://spongepowered.org || true
        wget -O libs/launchwrapper.jar https://minecraft.net
        wget -O libs/lwjgl.jar https://minecraft.net

    - name: Compilar Codigo Java
      run: |
        mkdir -p bin
        mkdir -p build/libs
        javac -cp "libs/*" -d bin src/main/java/com/example/examplemod/ExampleMod.java
        cd bin
        jar cvf ../build/libs/wtapstimp-1.0.0.jar .
      continue-on-error: true

    - name: Guardar el archivo JAR del Mod
      uses: actions/upload-artifact@v4
      with:
        name: WTapStimpMod-Listo
        path: build/libs/*.jar
